In [1]:
import pandas as pd
import numpy as np

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.model_selection import cross_val_score

from sklearn.compose import ColumnTransformer

In [9]:
df = pd.read_csv('train.csv')[['Age','Fare','SibSp','Parch','Survived']]

In [11]:
df.dropna(inplace=True)

In [13]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [17]:
df['family']=df['SibSp'] + df['Parch']

In [19]:
df.head()

    Age     Fare  SibSp  Parch  Survived  family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [25]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [27]:
df.head()

    Age     Fare  Survived  family
0  22.0   7.2500         0       1
1  38.0  71.2833         1       1
2  26.0   7.9250         1       0
3  35.0  53.1000         1       1
4  35.0   8.0500         0       0

In [29]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=43)

In [33]:
x_train.head()

      Age     Fare  family
83   28.0  47.1000       0
646  19.0   7.8958       0
635  28.0  13.0000       0
827   1.0  37.0042       2
685  25.0  41.5792       3

In [41]:

# Without binarization

clf = DecisionTreeClassifier()

clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)

accuracy_score(y_test,y_pred)

0.6503496503496503

In [47]:
np.mean(cross_val_score(DecisionTreeClassifier(),x,y,cv=10,scoring='accuracy'))

0.6541471048513301

In [49]:
# Applying Binarization

from sklearn.preprocessing import Binarizer

In [51]:
trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')

In [53]:
x_train_trf=trf.fit_transform(x_train)
x_test_trf=trf.transform(x_test)

In [55]:
pd.DataFrame(x_train_trf,columns=['family','Age','Fare'])

     family   Age      Fare
0       0.0  28.0   47.1000
1       0.0  19.0    7.8958
2       0.0  28.0   13.0000
3       1.0   1.0   37.0042
4       1.0  25.0   41.5792
..      ...   ...       ...
566     1.0  31.0   18.0000
567     0.0  25.0    7.6500
568     0.0  36.0   13.0000
569     1.0  31.0  164.8667
570     0.0  23.0   10.5000

[571 rows x 3 columns]

In [57]:
clf = DecisionTreeClassifier()
clf.fit(x_train_trf,y_train)
y_pred2 = clf.predict(x_test_trf)

accuracy_score(y_test,y_pred2)

0.6643356643356644

In [61]:

x_trf = trf.fit_transform(x)
np.mean(cross_val_score(DecisionTreeClassifier(),x_trf,y,cv=10,scoring='accuracy'))

0.6318075117370892