In [3]:
import pandas as pd
import numpy as np

In [5]:
date = pd.read_csv("C:/Users/sanke/Downloads/orders.csv")
time = pd.read_csv("C:/Users/sanke/Downloads/messages.csv")

In [9]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [26]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

# Working with dates

In [29]:
# Converting datetime datatype
date['date']=pd.to_datetime(date['date'])

In [31]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1.Extract year

In [39]:
date['date_year']=date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
555 2019-08-15        3422       13       2       2019
705 2018-10-21        7099       26       4       2018
552 2019-02-04        5955       16       3       2019
274 2019-01-22        5618       21       3       2019
364 2019-03-26        5687       13      11       2019

## 2.Extract Month

In [48]:
date['date_month_no']=date['date'].dt.month
date.head(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_no
0,2019-12-10,5628,25,3,2019,12,12
1,2018-08-15,3646,14,157,2018,8,8
2,2018-10-23,1859,25,1,2018,10,10
3,2019-08-17,7292,25,1,2019,8,8
4,2019-01-06,4344,25,3,2019,1,1

In [50]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,12,December
1,2018-08-15,3646,14,157,2018,8,8,August
2,2018-10-23,1859,25,1,2018,10,10,October
3,2019-08-17,7292,25,1,2019,8,8,August
4,2019-01-06,4344,25,3,2019,1,1,January

## Extract days

In [54]:
date['date_days'] =date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_no,date_month_name,date_days
0,2019-12-10,5628,25,3,2019,12,12,December,10
1,2018-08-15,3646,14,157,2018,8,8,August,15
2,2018-10-23,1859,25,1,2018,10,10,October,23
3,2019-08-17,7292,25,1,2019,8,8,August,17
4,2019-01-06,4344,25,3,2019,1,1,January,6

In [60]:
# Days of week
date['DOW']=date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_no,date_month_name,date_days,DOW
0,2019-12-10,5628,25,3,2019,12,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,1,January,6,6

In [68]:
# day of week name
date['date_dow_name']=date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_no,date_month_name,date_days,DOW,date_dow_name
0,2019-12-10,2019,12,12,December,10,1,Tuesday
1,2018-08-15,2018,8,8,August,15,2,Wednesday
2,2018-10-23,2018,10,10,October,23,1,Tuesday
3,2019-08-17,2019,8,8,August,17,5,Saturday
4,2019-01-06,2019,1,1,January,6,6,Sunday

In [72]:
# checking is weekend or not?
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_no,date_month_name,date_days,DOW,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,1,January,6,6,Sunday,1

# working on time

In [75]:
time['date']=pd.to_datetime(time['date'])

In [79]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [81]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

## Extract time part

In [84]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [87]:
## Time difference